// <auto-generated />
namespace WebSite.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddTagCount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTagCount));
        
        string IMigrationMetadata.Id
        {
            get { return "201303101244056_AddTagCount"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
